import { useState } from 'react';
import {
  Container,
  Stack,
  Breadcrumb,
  Tabs,
  TabList,
  Tab,
  TabPanel,
  Modal,
  Drawer,
  Field,
  Label,
  Input,
  Select,
  HelperText,
  Button,
  IconSparkles,
  IconWater,
  IconLeaf,
  IconSun,
  IconMonitor,
  WaterRipple,
  AeroCursor,
  AeroCursorMode,
  useToast,
} from '@frutiger.js/react';

// Modular Sections & Tabs
import { NavbarHeader } from './components/NavbarHeader';
import { HeroSection } from './components/HeroSection';
import { AeroWidgetsSection } from './components/AeroWidgetsSection';
import { AeroPrimitivesTab } from './components/AeroPrimitivesTab';
import { AeroButtonsTab } from './components/AeroButtonsTab';
import { AeroCardsTab } from './components/AeroCardsTab';
import { AeroFormsTab } from './components/AeroFormsTab';
import { AeroFeedbackTab } from './components/AeroFeedbackTab';
import { AeroNavigationTab } from './components/AeroNavigationTab';
import { AeroOverflowTab } from './components/AeroOverflowTab';
import { AeroArchiveTab } from './components/AeroArchiveTab';
import { AeroDesktopDemo } from './components/AeroDesktopDemo';
import { AeroIconExplorer } from './components/AeroIconExplorer';
import { AeroFaqTab } from './components/AeroFaqTab';
import { AeroResponsiveTab } from './components/AeroResponsiveTab';
import { TokensPaletteSection } from './components/TokensPaletteSection';
import { CreatorSection } from './components/CreatorSection';
import { FooterSection } from './components/FooterSection';

// Audio & utilities
import { playAeroChime, playAeroClick } from './utils/aeroAudio';

export default function App() {
  const [activeNav, setActiveNav] = useState('overview');
  const [selectedExplorerTab, setSelectedExplorerTab] = useState('primitives');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [sliderGainVal, setSliderGainVal] = useState(74);
  const [isWaterRippleEnabled, setIsWaterRippleEnabled] = useState(true);
  const [cursorMode, setCursorMode] = useState<AeroCursorMode>('droplet');

  const { toast } = useToast();

  const handleSelectCursorMode = (mode: AeroCursorMode) => {
    setCursorMode(mode);
    playAeroClick(sliderGainVal);
    const modeNames: Record<AeroCursorMode, string> = {
      droplet: 'Aero Water Droplet',
      crystal: 'Specular Crystal',
      nature: 'Biosphere Emerald',
      classic: 'Classic Web 2.0',
      default: 'System Native',
    };
    const modeIcons: Record<AeroCursorMode, React.ReactElement> = {
      droplet: <IconWater size={18} />,
      crystal: <IconSparkles size={18} />,
      nature: <IconLeaf size={18} />,
      classic: <IconSun size={18} />,
      default: <IconMonitor size={18} />,
    };
    toast({
      title: `Cursor: ${modeNames[mode]}`,
      description:
        mode === 'default'
          ? 'Reverted to native operating system cursor.'
          : `Activated ${modeNames[mode]} dynamic cursor preset.`,
      variant: 'info',
      icon: modeIcons[mode],
    });
  };

  const handleToggleWaterRipple = () => {
    const next = !isWaterRippleEnabled;
    setIsWaterRippleEnabled(next);
    playAeroClick(sliderGainVal);
    toast({
      title: next ? 'Water FX Active 💧' : 'Water FX Disabled 🔇',
      description: next
        ? 'Interactive water ripples and micro bubbles enabled on click.'
        : 'Water ripple effects paused.',
      variant: next ? 'info' : 'warning',
      icon: <IconWater size={18} />,
    });
  };

  const handleCopyInstall = () => {
    playAeroClick(sliderGainVal);
    navigator.clipboard.writeText('npm install @frutiger.js/core @frutiger.js/react');
    toast({
      title: 'Command Copied! 💧',
      description:
        'npm install @frutiger.js/core @frutiger.js/react has been copied to your clipboard.',
      variant: 'success',
      icon: <IconSparkles size={18} />,
    });
  };

  const handleExportTokens = () => {
    const cssContent = `/* 💧 Frutiger Aero CSS Design Tokens (Generated by Frutiger.js) */
@layer fj.tokens {
  :root {
    --fj-color-sky-50: #f0f9ff;
    --fj-color-sky-100: #e0f2fe;
    --fj-color-sky-200: #bae6fd;
    --fj-color-sky-300: #7dd3fc;
    --fj-color-sky-400: #38bdf8;
    --fj-color-sky-500: #0ea5e9;
    --fj-color-sky-600: #0284c7;
    --fj-color-sky-700: #0369a1;
    --fj-color-sky-800: #075985;
    --fj-color-sky-900: #0c4a6e;
    --fj-color-sky-950: #082f49;

    --fj-color-grass-500: #22c55e;
    --fj-color-water-400: #38bdf8;
    --fj-color-sun-400: #facc15;
    
    --fj-glass-bg: rgba(255, 255, 255, 0.75);
    --fj-glass-border: 1px solid rgba(255, 255, 255, 0.95);
    --fj-glass-shadow: 0 12px 36px rgba(2, 132, 199, 0.2), inset 0 1px 1px #ffffff;
    --fj-glass-blur: blur(20px) saturate(180%);
  }
}
`;
    const blob = new Blob([cssContent], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'frutiger-tokens.css';
    a.click();
    URL.revokeObjectURL(url);
    playAeroChime(sliderGainVal);
    toast({
      title: 'Tokens Exported! 💧',
      description: 'Downloaded frutiger-tokens.css to your machine.',
      variant: 'success',
      icon: <IconSparkles size={18} />,
    });
  };

  const handleExportComponents = () => {
    const pkg = {
      name: '@frutiger.js/components',
      version: '1.10.0',
      components: [
        'Button',
        'Card',
        'Input',
        'Dropdown',
        'DropdownSelect',
        'SegmentedControl',
        'WindowFrame',
        'Taskbar',
        'StartMenu',
        'Dropzone',
        'Tabs',
        'Slider',
        'Badge',
        'Alert',
      ],
      author: 'Biagio Scaglia',
      url: 'https://biagiocyberspace.it/frutiger-js',
    };
    const blob = new Blob([JSON.stringify(pkg, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'frutiger-manifest.json';
    a.click();
    URL.revokeObjectURL(url);
    playAeroChime(sliderGainVal);
    toast({
      title: 'Package Manifest Exported! ✨',
      description: 'Downloaded frutiger-manifest.json successfully.',
      variant: 'success',
    });
  };

  return (
    <div className="fj-bg-aero" style={{ minHeight: '100vh' }}>
      {/* Interactive Water Ripple & Bubble Overlay */}
      <WaterRipple
        enabled={isWaterRippleEnabled}
        showBubbles={true}
        ambientBubbles={true}
        colorScheme="sky"
      />

      {/* Custom Aero Cursor (Desktop Only) */}
      <AeroCursor mode={cursorMode} />

      {/* Top Aero Header */}
      <NavbarHeader
        activeNav={activeNav}
        onNavClick={setActiveNav}
        isWaterRippleEnabled={isWaterRippleEnabled}
        onToggleWaterRipple={handleToggleWaterRipple}
        cursorMode={cursorMode}
        onSelectCursorMode={handleSelectCursorMode}
        onExploreIcons={() => {
          setActiveNav('icons');
          setSelectedExplorerTab('icons');
        }}
        onExploreResponsive={() => {
          setActiveNav('responsive-lab');
          setSelectedExplorerTab('responsive');
        }}
      />

      {/* Main Content */}
      <main id="main-content" role="main">
        <Container size="xl" style={{ paddingTop: '2.5rem', paddingBottom: '4rem' }}>
          <Stack spacing="xl">
            {/* Hero Banner */}
            <HeroSection
              onCopyInstall={handleCopyInstall}
              onExploreIcons={() => setSelectedExplorerTab('icons')}
            />

            {/* Breadcrumb Demo */}
            <div style={{ padding: '0 0.5rem' }}>
              <Breadcrumb
                items={[
                  { label: 'Home', href: '#' },
                  { label: 'Design System', href: '#components' },
                  { label: 'Frutiger Aero Playground', isActive: true },
                ]}
              />
            </div>

            {/* Memoized Aero Desktop Widgets Showcase */}
            <AeroWidgetsSection />

            {/* Interactive Component Explorer Tabs */}
            <section id="components" aria-labelledby="components-heading">
              <h2
                id="components-heading"
                style={{
                  fontSize: 'var(--fj-font-size-2xl)',
                  fontWeight: 700,
                  marginBottom: '1.25rem',
                  color: 'var(--fj-color-text)',
                }}
              >
                Interactive Component Explorer
              </h2>

              <Tabs value={selectedExplorerTab} onValueChange={setSelectedExplorerTab}>
                <TabList>
                  <Tab value="primitives">Aero Primitives</Tab>
                  <Tab value="buttons">Buttons</Tab>
                  <Tab value="cards">Cards & Surfaces</Tab>
                  <Tab value="forms">Form Controls</Tab>
                  <Tab value="feedback">Alerts & Badges</Tab>
                  <Tab value="navigation">Tabs & Accordion</Tab>
                  <Tab value="overflow">Custom Overflow</Tab>
                  <Tab value="archive">Aero Gallery & Archive</Tab>
                  <Tab value="window">Aero Desktop & Taskbar</Tab>
                  <Tab value="icons">Aero Custom Icons</Tab>
                  <Tab value="faq">FAQ Knowledgebase</Tab>
                  <Tab value="responsive">Responsive Lab</Tab>
                </TabList>

                {/* 1. PRIMITIVES */}
                <TabPanel value="primitives">
                  <AeroPrimitivesTab />
                </TabPanel>

                {/* 2. BUTTONS */}
                <TabPanel value="buttons">
                  <AeroButtonsTab sliderGainVal={sliderGainVal} />
                </TabPanel>

                {/* 3. CARDS */}
                <TabPanel value="cards">
                  <AeroCardsTab />
                </TabPanel>

                {/* 4. FORMS */}
                <TabPanel value="forms">
                  <AeroFormsTab sliderGainVal={sliderGainVal} onGainChange={setSliderGainVal} />
                </TabPanel>

                {/* 5. FEEDBACK */}
                <TabPanel value="feedback">
                  <AeroFeedbackTab
                    onOpenDrawer={() => setIsDrawerOpen(true)}
                    sliderGainVal={sliderGainVal}
                  />
                </TabPanel>

                {/* 6. NAVIGATION */}
                <TabPanel value="navigation">
                  <AeroNavigationTab
                    onOpenDrawer={() => setIsDrawerOpen(true)}
                    sliderGainVal={sliderGainVal}
                    onExportTokens={handleExportTokens}
                    onExportComponents={handleExportComponents}
                  />
                </TabPanel>

                {/* 7. OVERFLOW */}
                <TabPanel value="overflow">
                  <AeroOverflowTab />
                </TabPanel>

                {/* 8. ARCHIVE */}
                <TabPanel value="archive">
                  <AeroArchiveTab />
                </TabPanel>

                {/* 9. WINDOW & DESKTOP */}
                <TabPanel value="window">
                  <AeroDesktopDemo />
                </TabPanel>

                {/* 10. ICONS */}
                <TabPanel value="icons">
                  <AeroIconExplorer />
                </TabPanel>

                {/* 11. FAQ */}
                <TabPanel value="faq">
                  <AeroFaqTab />
                </TabPanel>

                {/* 12. RESPONSIVE */}
                <TabPanel value="responsive">
                  <AeroResponsiveTab />
                </TabPanel>
              </Tabs>
            </section>

            {/* Design Tokens Palette Section */}
            <TokensPaletteSection />

            {/* Biagio Scaglia - Creator & Architect Section */}
            <CreatorSection />
          </Stack>
        </Container>
      </main>

      {/* Interactive Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Welcome to Frutiger.js"
      >
        <p style={{ marginBottom: '1.25rem', lineHeight: 1.6 }}>
          You have successfully initialized <strong>Frutiger.js</strong>. Enjoy the crisp glossy
          surfaces, specular dome highlights, and natural digital textures!
        </p>
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem' }}>
          <Button variant="ghost" onClick={() => setIsModalOpen(false)}>
            Cancel
          </Button>
        </div>
      </Modal>

      {/* Interactive Aero Slide Drawer */}
      <Drawer
        isOpen={isDrawerOpen}
        onClose={() => setIsDrawerOpen(false)}
        title="Aero Slide-Over Workspace"
        placement="right"
        footer={
          <>
            <Button variant="ghost" onClick={() => setIsDrawerOpen(false)}>
              Dismiss
            </Button>
            <Button variant="primary" onClick={() => setIsDrawerOpen(false)}>
              Apply Changes
            </Button>
          </>
        }
      >
        <Stack spacing="md">
          <p style={{ margin: 0, fontSize: '0.9375rem', lineHeight: 1.5 }}>
            This slide-over drawer is rendered with acrylic hardware-accelerated glass backdrop
            filters, specular rim highlights, and complete WCAG 2.2 keyboard navigation (ESC key
            dismiss).
          </p>

          <Field>
            <Label isRequired htmlFor="drawer-preset">
              Workspace Name
            </Label>
            <Input id="drawer-preset" defaultValue="Aero Biosphere Lab" />
            <HelperText>Visible to all synchronized network nodes.</HelperText>
          </Field>

          <Field>
            <Label htmlFor="drawer-mode">Rendering Pipeline</Label>
            <Select
              id="drawer-mode"
              options={[
                { value: 'vulkan', label: 'Hardware Accelerated Glass' },
                { value: 'directx', label: 'DirectX Acrylic Shaders' },
                { value: 'webgl', label: 'WebGL Water Caustics' },
              ]}
            />
          </Field>
        </Stack>
      </Drawer>

      {/* Footer */}
      <FooterSection />
    </div>
  );
}
